import Head from 'next/head'
import Link from "next/link";
import Image from 'next/image'
import { useRouter } from "next/router";
import styles from '../styles/Home.module.css'
import useI18n from "../hooks/use-i18n";
import Title from "../components/title";

export default function Home() {
  const router = useRouter();
  const { locales } = router;
  const i18n = useI18n();
  return (
    <div className={styles.container}>
      <Head>
        <title>{i18n.t('intro.welcome')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
        {i18n.t('intro.welcome')} <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link
            href={`/${locales
              .filter((lng) => lng !== i18n.activeLocale)
              .reduce((_, cur) => `${cur}`)}`}
            locale={`${locales
              .filter((lng) => lng !== i18n.activeLocale)
              .reduce((_, cur) => `${cur}`)}`}
          >
            <a>Use cient-side routing to change language to 'de'</a>
          </Link>
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <Title username="Peter" />

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export async function getStaticProps(context) {
  const { locale } = context;
  const { default: lngDict = {} } = await import(`../locales/${locale}.json`);

  return {
    props: { lng: locale, lngDict },
  };
}