import Head from 'next/head'
import Link from "next/link";
import Image from 'next/image'
import { useRouter } from "next/router";
import styles from '../styles/Home.module.scss'
import useI18n from "../hooks/use-i18n";
import Title from "../components/title";

import MainLayout from '../layouts/mainLayout'
import { httpGet } from '../service/http'
import urls from '../service/urls'
import NewsModule from '../components/index/news/news'
import CenterContainer from '../components/index/centerContent/centerContainer'
import { Carousel, Popover } from 'antd';
import React, { useRef, useState } from 'react'
import { LeftOutlined, RightOutlined } from '@ant-design/icons'

export default function Home({ info, newsList, ...props }) {
  const router = useRouter();
  const { locales } = router;
  const i18n = useI18n();


  const swiperRef = useRef()
  const [cur, setCur] = useState(0)
  const preHandler = function () {
    swiperRef.current.prev()
  }
  const nextHandler = function () {
    swiperRef.current.next()
  }
  const dotHandler = function (current) {
    swiperRef.current.goTo(current)
  }
  const setChangeDot = function (from, to) {
    setCur(to)
  }
  const mediaList = [
    { icon: 'icon-weixin', src: '/images/logo.png' },
    { icon: 'icon-qq-circle', src: '/images/logo.png', openLink: true }
  ]
  const linkList = [
    {
      title: '产品中心',
      children: [
        { title: '热门产品', link: '/productCenter' },
        { title: '最新上架', link: '/productCenter' },
        { title: '创新产品', link: '/productCenter' }
      ]
    },
    {
      title: '加入非夕',
      children: [
        { title: '福利待遇', link: '/join?type=1' },
        { title: '员工风采', link: '/about?type=3' },
        { title: '员工发展', link: '/about?type=4' },
        { title: '招聘岗位', link: '/join?type=0' }
      ]
    },
    {
      title: '关于飞夕',
      children: [
        { title: '公司简介', link: '/about?type=0' },
        { title: '发展历程', link: '/about?type=1' },
        { title: '公司文化', link: '/about?type=2' }
      ]
    }
  ]
  const OPEN_KF_HANDLER = () => {
    window.open('tencent://message/?uin=800183557&Site=在线QQ&amp;Menu=yes')
    // tencent://message/?uin=800183557&Site=在线QQ&amp;Menu=yes
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>{i18n.t('intro.welcome')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
      <main className={styles.main}>
        {/* <h1 className={styles.title}>
        {i18n.t('intro.welcome')} <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link
            href={`/${locales
              .filter((lng) => lng !== i18n.activeLocale)
              .reduce((_, cur) => `${cur}`)}`}
            
          >
            <a>Use cient-side routing to change language to 'de'</a>
          </Link>
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <Title username="Peter" />

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
        <div className={styles.swiperOut}>
            {/* 轮播方向箭头 */}
            <div className={[styles.controlContainer, 'flex-col', 'flex-ali-center', 'flex-jst-start'].join(' ')}>
              <div className={[styles.controlBar, 'flex-row', 'flex-jst-btw', 'flex-ali-center'].join(' ')}>
                <div className={['flex-row', 'flex-jst-center', 'flex-ali-center', styles.controlArrow].join(' ')} onClick={() => preHandler()}>
                  <LeftOutlined style={{fontSize:'20px'}}/>
                </div>
                {/* 向右 */}
                <div className={['flex-row', 'flex-jst-center', 'flex-ali-center', styles.controlArrow, styles.controlArrowRight].join(' ')} onClick={() => nextHandler()}>
                  <RightOutlined style={{fontSize:'20px'}}/>
                </div>
              </div>
              {/* 轮播点 */}
              <div className={['full-width', 'flex-row', 'flex-jst-center', 'flex-ali-center', styles.dotContainer].join(' ')}>
                {
                  info.banners.map((item, idx) => {
                    return (
                      <div className={[styles.cusDot, cur === idx ? styles.curDot : ''].join(' ')} key={item} onClick={() => dotHandler(idx)}></div>
                    )
                  })
                }
              </div>
              {/* 新闻模块 */}
              <NewsModule gameList={info.games.list.filter(item => item.is_hot).slice(0, 5)} newsList={newsList.slice(0, 8)}></NewsModule>
            </div>
            <Carousel effect="fade" dots={false} autoplay={true} ref={swiperRef} beforeChange={(from, to) => setChangeDot(from, to)}>
              {info.banners.map(item => {
                return (
                  <div className={styles.swiperItem} key={item}>
                    <img src={item} alt="" />
                  </div>
                )
              })}
            </Carousel>
          </div>
          {/* 中间部分 */}
          <div className={styles.centerOut}>
            <CenterContainer gameList={info.games.list} packageList={info.news} newsList={newsList.slice(0, 3)}></CenterContainer>
          </div>
          {/* 链接部分 */}
          <div className={styles.linkArea}>
            <div className={[styles.contArea, 'flex-row', 'flex-jst-btw', 'flex-ali-start'].join(' ')}>
              <div className={['flex-col', 'flex-jst-start', 'flex-ali-start'].join(' ')}>
                <div className={['full-width', 'flex-row', 'flex-jst-start', 'flex-ali-center', styles.concat].join(' ')}>
                  <div className={[styles.iconOut]}>
                    <i className='iconfont icon-youjian'></i>
                  </div>
                  <div className={[styles.linkInfo, 'flex-col', 'flex-jst-center', 'flex-ali-start', 'self-stretch'].join(' ')}>
                    <p>邮箱地址：</p>
                    <span>business@flexiv.com</span>
                  </div>
                </div>
                <div className={['full-width', 'flex-row', 'flex-jst-start', 'flex-ali-center', styles.concat].join(' ')}>
                  <div className={[styles.iconOut]}>
                    <i className='iconfont icon-telephone'></i>
                  </div>
                  <div className={[styles.linkInfo, 'flex-col', 'flex-jst-center', 'flex-ali-start', 'self-stretch'].join(' ')}>
                    <p>联系电话：</p>
                    <span>+86 400 8888 105 (中国)</span>
                  </div>
                </div>
                {/* 微博微信QQ */}
                <div className={['flex-row', 'flex-jst-start', 'flex-ali-center', styles.mediaList].join(' ')}>
                  {
                    mediaList.map((item, idx) => {
                      return item.openLink ? (
                        <i className={`iconfont ${item.icon} cursor-pointer`} style={{ fontSize: '.4rem', color: '#3c4043', marginLeft: idx === 0 ? '' : '.35rem' }} onClick={() => OPEN_KF_HANDLER()} key={idx}></i>
                      ) :
                        (
                          <Popover content={
                            <img src={item.src} style={{ width: '1.5rem', height: '1.5rem' }}></img>
                          } key={idx}>
                            <i className={`iconfont ${item.icon} cursor-pointer`} style={{ fontSize: '.4rem', color: '#3c4043', marginLeft: idx === 0 ? '' : '.35rem' }}></i>
                          </Popover>
                        )
                    })
                  }
                </div>
              </div>
              <div className={['flex-3', 'flex-row', 'flex-jst-btw', styles.menuList].join(' ')}>
                {
                  linkList.map(item => {
                    return (
                      <div className={['flex-col', 'flex-jst-start', 'flex-ali-start', styles.menuCol].join(' ')} key={item.title}>
                        <p className={styles.title}>{item.title}</p>
                        {
                          item.children.map(ele => {
                            return (
                              <Link href={ele.link} key={ele.title}>
                                <span className={styles.menuItem}>{ele.title}</span>
                              </Link>
                            )
                          })
                        }
                      </div>
                    )
                  })
                }
              </div>
              <div className={['self-stretch', 'flex-col', 'flex-jst-center', 'flex-ali-center'].join(' ')}>
                <img src="/images/logo.png" alt="" className='self-stretch' style={{display: 'block', height: '1.6rem', width: '1.6rem'}}/>
                <p className='title-font font-20'>非夕官方公众号</p>
              </div>
            </div>
          </div>
      </main>
      </MainLayout>
    </div>
  )
}
export async function getStaticProps(context) {
  const { locale } = context;
  const { default: lngDict = {} } = await import(`../locales/${locale}.json`);
  // const { data } = await httpGet(urls.queryIndex);
  const data = await {
    banners:['https://www.flexiv.cn/cn/assets/solution/banner.png','https://www.flexiv.cn/cn/assets/home/card1.png','https://www.flexiv.cn/cn/assets/home/home1.jpg'],
    packages: [
      {
        id: 9,
        game_id: 9,
        package_name: 'flexiv',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: 'flexiv-flexiv',
        download_link: 'https://www.flexiv.cn/',
        android_link: null,
        switch: 1,
        created_at: '2021-04-20 18:31:38',
        updated_at: null
      },
      {
        id: 8,
        game_id: 8,
        package_name: 'flexiv',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: 'flexiv-flexiv',
        download_link: 'https://www.flexiv.cn/cn/',
        android_link: null,
        switch: 1,
        created_at: '2021-03-25 18:39:27',
        updated_at: '2021-04-20 17:30:44'
      },
      {
        id: 7,
        game_id: 7,
        package_name: 'flexiv',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: 'flexiv-flexiv',
        download_link: 'https://www.flexiv.cn/',
        android_link: null,
        switch: 1,
        created_at: '2021-03-25 18:33:29',
        updated_at: null
      },
      {
        id: 6,
        game_id: 6,
        package_name: 'flexiv',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: 'flexiv-flexiv',
        download_link: 'https://www.flexiv.cn/',
        android_link: null,
        switch: 1,
        created_at: '2021-03-25 17:11:56',
        updated_at: null
      },
      {
        id: 5,
        game_id: 5,
        package_name: 'flexiv',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: 'flexiv-flexiv',
        download_link: 'https://www.flexiv.cn/',
        android_link: null,
        switch: 1,
        created_at: '2021-03-25 16:58:30',
        updated_at: null
      },
      {
        id: 4,
        game_id: 2,
        package_name: '女武神降临-魔幻卡牌养成手游',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: 'flexiv-flexiv',
        download_link: 'https://www.flexiv.cn/',
        android_link: null,
        switch: 1,
        created_at: '2021-03-24 17:51:26',
        updated_at: '2021-03-24 18:54:06'
      },
      {
        id: 3,
        game_id: 3,
        package_name: 'flexiv',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: 'flexiv-flexiv',
        download_link: 'https://www.flexiv.cn',
        android_link: null,
        switch: 1,
        created_at: '2021-03-24 17:50:21',
        updated_at: '2021-03-24 18:53:09'
      },
      {
        id: 2,
        game_id: 4,
        package_name: 'flexiv',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: 'flexiv-flexiv',
        download_link: 'https://www.flexiv.cn',
        android_link: null,
        switch: 1,
        created_at: '2021-03-24 17:48:23',
        updated_at: '2021-04-20 17:29:17'
      },
      {
        id: 1,
        game_id: 1,
        package_name: 'flexiv',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: 'flexiv-flexiv',
        download_link: 'https://www.flexiv.cn',
        android_link: null,
        switch: 1,
        created_at: '2021-03-24 17:46:28',
        updated_at: '2021-04-20 17:25:36'
      }
    ],
    games:{
      list: [
        {
          id: 9,
          name: '拂晓',
          subtitle: '自适应机器人能够创造哪些价值',
          poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          hot_background: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          introduction: '自适应机器人能够创造哪些价值',
          domain: 'https://apps.apple.com/cn/app/id1561136709',
          is_hot: 0,
          is_publish: 1,
          created_at: '2021-04-20 18:30:19',
          update_at: null
        },
        {
          id: 8,
          name: '拂晓',
          subtitle: '自适应机器人能够创造哪些价值',
          poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          hot_background: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          introduction: '自适应机器人能够创造哪些价值',
          domain: 'https://apps.apple.com/cn/app/id1561921656',
          is_hot: 0,
          is_publish: 1,
          created_at: '2021-03-25 18:38:23',
          update_at: '2021-04-20 17:29:43'
        },
        {
          id: 7,
          name: '拂晓',
          subtitle: '自适应机器人能够创造哪些价值',
          poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          hot_background: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          introduction: '自适应机器人能够创造哪些价值',
          domain: 'https://apps.apple.com/cn/app/id1481456070',
          is_hot: 0,
          is_publish: 1,
          created_at: '2021-03-25 18:30:46',
          update_at: '2021-04-20 13:45:00'
        },
        {
          id: 6,
          name: '拂晓',
          subtitle: '自适应机器人能够创造哪些价值',
          poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          hot_background: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          introduction: '自适应机器人能够创造哪些价值',
          domain: 'https://apps.apple.com/cn/app/id1459988269',
          is_hot: 0,
          is_publish: 1,
          created_at: '2021-03-25 17:09:59',
          update_at: '2021-04-20 17:31:17'
        },
        {
          id: 5,
          name: '拂晓',
          subtitle: '自适应机器人能够创造哪些价值',
          poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          hot_background: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          introduction: '自适应机器人能够创造哪些价值',
          domain: 'https://apps.apple.com/cn/app/id1517970763',
          is_hot: 0,
          is_publish: 1,
          created_at: '2021-03-25 16:52:29',
          update_at: '2021-04-20 13:46:08'
        },
        {
          id: 4,
          name: '拂晓',
          subtitle: '自适应机器人能够创造哪些价值',
          poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          hot_background: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          introduction: '自适应机器人能够创造哪些价值',
          domain: 'https://apps.apple.com/cn/app/id1551263818',
          is_hot: 1,
          is_publish: 1,
          created_at: '2021-03-24 17:31:48',
          update_at: '2021-04-20 17:28:59'
        },
        {
          id: 3,
          name: '拂晓',
          subtitle: '自适应机器人能够创造哪些价值',
          poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          hot_background: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          introduction: '自适应机器人能够创造哪些价值',
          domain: 'https://apps.apple.com/cn/app/id1554998683',
          is_hot: 1,
          is_publish: 1,
          created_at: '2021-03-24 17:28:59',
          update_at: '2021-04-20 13:46:37'
        },
        {
          id: 2,
          name: '拂晓',
          subtitle: '自适应机器人能够创造哪些价值',
          poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          hot_background: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          introduction: '自适应机器人能够创造哪些价值',
          domain: 'https://apps.apple.com/cn/app/id1551768868',
          is_hot: 1,
          is_publish: 1,
          created_at: '2021-03-24 17:26:22',
          update_at: '2021-04-20 17:25:57'
        },
        {
          id: 1,
          name: '拂晓',
          subtitle: '自适应机器人能够创造哪些价值',
          poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          hot_background: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
          introduction: '自适应机器人能够创造哪些价值',
          domain: 'https://apps.apple.com/cn/app/id1561916878',
          is_hot: 1,
          is_publish: 1,
          created_at: '2021-03-24 17:22:08',
          update_at: '2021-04-20 17:24:18'
        }
      ],
      total: 9
    },
    news: [
      {
        id: 9,
        game_id: 9,
        package_name: 'flexiv-拂晓',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: '自适应机器人能够创造哪些价值',
        download_link: 'https://apps.apple.com/cn/app/id1561136709',
        android_link: null,
        switch: 1,
        created_at: '2021-04-20 18:31:38',
        updated_at: null
      },
      {
        id: 8,
        game_id: 8,
        package_name: 'flexiv-拂晓',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: '自适应机器人能够创造哪些价值',
        download_link: 'https://apps.apple.com/cn/app/id1561136709',
        android_link: null,
        switch: 1,
        created_at: '2021-04-20 18:31:38',
        updated_at: null
      },
      {
        id: 7,
        game_id: 7,
        package_name: 'flexiv-拂晓',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: '自适应机器人能够创造哪些价值',
        download_link: 'https://apps.apple.com/cn/app/id1561136709',
        android_link: null,
        switch: 1,
        created_at: '2021-04-20 18:31:38',
        updated_at: null
      },
      {
        id: 6,
        game_id: 6,
        package_name: 'flexiv-拂晓',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: '自适应机器人能够创造哪些价值',
        download_link: 'https://apps.apple.com/cn/app/id1561136709',
        android_link: null,
        switch: 1,
        created_at: '2021-04-20 18:31:38',
        updated_at: null
      },
      {
        id: 5,
        game_id: 5,
        package_name: 'flexiv-拂晓',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: '自适应机器人能够创造哪些价值',
        download_link: 'https://apps.apple.com/cn/app/id1561136709',
        android_link: null,
        switch: 1,
        created_at: '2021-04-20 18:31:38',
        updated_at: null
      },
      {
        id: 4,
        game_id: 2,
        package_name: 'flexiv-拂晓',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: '自适应机器人能够创造哪些价值',
        download_link: 'https://apps.apple.com/cn/app/id1561136709',
        android_link: null,
        switch: 1,
        created_at: '2021-04-20 18:31:38',
        updated_at: null
      },
      {
        id: 3,
        game_id: 3,
        package_name: 'flexiv-拂晓',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: '自适应机器人能够创造哪些价值',
        download_link: 'https://apps.apple.com/cn/app/id1561136709',
        android_link: null,
        switch: 1,
        created_at: '2021-04-20 18:31:38',
        updated_at: null
      },
      {
        id: 2,
        game_id: 4,
        package_name: 'flexiv-拂晓',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: '自适应机器人能够创造哪些价值',
        download_link: 'https://apps.apple.com/cn/app/id1561136709',
        android_link: null,
        switch: 1,
        created_at: '2021-04-20 18:31:38',
        updated_at: null
      },
      {
        id: 1,
        game_id: 1,
        package_name: 'flexiv-拂晓',
        poster: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        logo: 'https://www.flexiv.cn/cn/assets/home/home1.jpg',
        description: '自适应机器人能够创造哪些价值',
        download_link: 'https://apps.apple.com/cn/app/id1561136709',
        android_link: null,
        switch: 1,
        created_at: '2021-04-20 18:31:38',
        updated_at: null
      }
    ]
  }
  // const newsRes = await httpGet(urls.queryNewsList)
  const newsList = [
    {
      id: 5,
      title: 'flexiv',
      content: '<p>自适应机器人能够创造哪些价值</p>',
      type: 1,
      created_at: '2021-03-25 14:54:52',
      updated_at: '2021-04-29 10:45:20'
    },
    {
      id: 4,
      title: 'flexiv',
      content: 
        '<p>自适应机器人能够创造哪些价值</p>\n' +
        '<p>本次更新内容如下</p>',
      type: 2,
      created_at: '2021-03-25 10:23:48',
      updated_at: '2021-03-25 19:08:27'
    },
    {
      id: 3,
      title: 'flexiv',
      content: '<p>自适应机器人能够创造哪些价值</p>\n' +
        '<p>自适应机器人能够创造哪些价值</p>\n' +
        '<p>感谢各位的谅解！祝您产品愉快！</p>\n' +
        '<p>涉及区服：535-538</p>',
      type: 2,
      created_at: '2021-03-25 10:19:04',
      updated_at: '2021-04-20 21:42:36'
    },
    {
      id: 2,
      title: 'flexiv',
      content: `<p><span style="background-color: #ffffff; color: #333333; font-family: -apple-system, system-ui, 'Helvetica Neue', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; letter-spacing: 1.5px; text-align: justify;"><img style="display: block; margin-left: auto; margin-right: auto;" src="http://img.web.8xgame.cn/news/6ea1e2e799f8c76bce526b565d505bd8.gif" alt="" width="400" height="388" /><br /></span></p>\n` +
        `<p style="text-align: center;"><span style="background-color: #ffffff; color: #333333; font-family: -apple-system, system-ui, 'Helvetica Neue', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; letter-spacing: 1.5px; text-align: justify;">虽然炎热的天气并没有走开</span></p>\n` +
        `<p style="text-align: center;"><span style="background-color: #ffffff; color: #333333; font-family: -apple-system, system-ui, 'Helvetica Neue', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; letter-spacing: 1.5px; text-align: justify;">夏天的美好幻想依然浮现在脑海中～</span></p>\n` +
        `<p style="text-align: center;"><span style="background-color: #ffffff; color: #333333; font-family: -apple-system, system-ui, 'Helvetica Neue', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI', 'Microsoft YaHei', Arial, sans-serif; font-size: 14px; letter-spacing: 1.5px; text-align: justify;">比如大海、沙滩、泳装、美女......</span></p>`,
      type: 3,
      created_at: '2021-03-24 16:49:26',
      updated_at: '2021-04-20 21:44:53'
    },
    {
      id: 1,
      title: 'flexiv',
      content: '<p>自适应机器人能够创造哪些价值</p>\n' +
        '<p>自适应机器人能够创造哪些价值</p>\n' +
        '<p>感谢各位的谅解！祝您产品愉快！</p>',
      type: 1,
      created_at: '2021-03-24 16:22:48',
      updated_at: null
    }
  ]
  data.packages.forEach(item => {
    item.gameName = data.games.list.find(ele => ele.id === item.game_id) ? data.games.list.find(ele => ele.id === item.game_id).name : '未命名'
  })
  return {
    props: { 
      lng: locale, 
      lngDict,
      info: data,
      newsList: newsList.splice(0, 10)//newsRes.data.list.splice(0, 10)
    }, // will be passed to the page component as props
  };
}